name: Erlang CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:

  build:
    strategy:
      matrix:
        erlvsn: [22, 23, 24, 25]

    runs-on: ubuntu-latest

    container:
      image: erlang:${{ matrix.erlvsn }}

    steps:
    - uses: actions/checkout@v3
    - name: Compile
      run: rebar3 compile
    - name: Run tests
      run: rebar3 do eunit, ct
